/* SPDX-License-Identifier: GPL-2.0-or-later */

/* Boot-time wallpaper cache.
 *
 * Decoding a JPEG/PNG and scaling it to the desktop size is real CPU
 * on an unaccelerated PXA255 -- and mbdesktop_view_init_bg() used to
 * pay that cost on *every* launch, including every single boot, even
 * though the wallpaper never changes between boots. This caches the
 * fully composited, desktop-sized, already-pixel-format-converted
 * result as a raw byte dump, so a normal boot is just an fread()
 * straight into the image buffer -- no decode, no scale, no color
 * conversion.
 *
 * The cache is invalidated (and silently regenerated by the caller)
 * whenever the resolved spec (mode + source filename), the desktop
 * dimensions, the pixbuf's internal pixel format, or the source
 * file's mtime no longer match what is recorded in the header.
 */

#include "mbdesktop_bg_cache.h"

#include <stdint.h>

#define WPCACHE_MAGIC   "MBWC"
#define WPCACHE_VERSION 1
#define WPCACHE_HDR_LEN 24

static char *
_cache_path(void)
{
  static char path[512];
  const char *home = mb_util_get_homedir();

  if (home == NULL || home[0] == '\0')
    snprintf(path, sizeof(path), "%s/wallpaper.cache", MBCONFDIR);
  else
    snprintf(path, sizeof(path), "%s/.matchbox/wallpaper.cache", home);

  return path;
}

/* Simple FNV-1a -- collisions are harmless here (worst case: one
 * stale cache read that gets overwritten after a re-decode), so
 * there is no need for anything stronger. */
static uint32_t
_hash_spec(MBDesktop *mb)
{
  uint32_t h = 2166136261u;
  const char *type_tag;
  const unsigned char *p;

  switch (mb->bg->type)
    {
    case BG_TILED_PXM:     type_tag = "tiled:";     break;
    case BG_STRETCHED_PXM: type_tag = "stretched:"; break;
    case BG_CENTERED_PXM:  type_tag = "centered:";  break;
    case BG_FILLED_PXM:    type_tag = "filled:";    break;
    default:               type_tag = "unknown:";   break;
    }

  for (p = (const unsigned char *)type_tag; *p; p++)
    { h ^= *p; h *= 16777619u; }

  for (p = (const unsigned char *)mb->bg->data.filename; p && *p; p++)
    { h ^= *p; h *= 16777619u; }

  return h;
}

static void
_put_u32(unsigned char *p, uint32_t v)
{
  p[0] = (unsigned char)(v & 0xff);
  p[1] = (unsigned char)((v>>8)  & 0xff);
  p[2] = (unsigned char)((v>>16) & 0xff);
  p[3] = (unsigned char)((v>>24) & 0xff);
}

static uint32_t
_get_u32(const unsigned char *p)
{
  return (uint32_t)p[0]         | ((uint32_t)p[1]<<8) |
         ((uint32_t)p[2]<<16)   | ((uint32_t)p[3]<<24);
}

MBPixbufImage *
mbdesktop_bg_cache_load(MBDesktop *mb)
{
  FILE *fp;
  unsigned char hdr[WPCACHE_HDR_LEN];
  struct stat st;
  uint32_t width, height, spec_hash, src_mtime;
  int has_alpha, bytespp;
  size_t pixel_bytes;
  MBPixbufImage *img;

  if (mb->bg == NULL || mb->bg->data.filename == NULL)
    return NULL;

  /* Source vanished -- let the normal decode path fail loudly instead
   * of silently serving stale cached pixels. */
  if (stat(mb->bg->data.filename, &st))
    return NULL;

  fp = fopen(_cache_path(), "rb");
  if (fp == NULL) return NULL;

  if (fread(hdr, 1, WPCACHE_HDR_LEN, fp) != WPCACHE_HDR_LEN
      || memcmp(hdr, WPCACHE_MAGIC, 4) != 0
      || hdr[4] != WPCACHE_VERSION)
    {
      fclose(fp);
      return NULL;
    }

  bytespp   = hdr[5];
  has_alpha = hdr[6];
  width     = _get_u32(hdr + 8);
  height    = _get_u32(hdr + 12);
  spec_hash = _get_u32(hdr + 16);
  src_mtime = _get_u32(hdr + 20);

  if (bytespp      != mb->pixbuf->internal_bytespp
      || (int)width  != mb->desktop_width
      || (int)height != mb->desktop_height
      || spec_hash   != _hash_spec(mb)
      || src_mtime   != (uint32_t)st.st_mtime)
    {
      fclose(fp);
      return NULL;
    }

  img = has_alpha
    ? mb_pixbuf_img_rgba_new(mb->pixbuf, (int)width, (int)height)
    : mb_pixbuf_img_rgb_new(mb->pixbuf, (int)width, (int)height);

  pixel_bytes = (size_t)width * (size_t)height
              * (size_t)(bytespp + (has_alpha ? 1 : 0));

  if (fread(img->rgba, 1, pixel_bytes, fp) != pixel_bytes)
    {
      mb_pixbuf_img_free(mb->pixbuf, img);
      fclose(fp);
      return NULL;
    }

  fclose(fp);

  return img;
}

void
mbdesktop_bg_cache_save(MBDesktop *mb, MBPixbufImage *img)
{
  char *path = _cache_path();
  char tmp_path[544];
  char dirpath[512];
  FILE *fp;
  unsigned char hdr[WPCACHE_HDR_LEN];
  struct stat st;
  size_t pixel_bytes;
  const char *home;

  if (mb->bg == NULL || mb->bg->data.filename == NULL) return;
  if (stat(mb->bg->data.filename, &st)) return;

  /* Make sure ~/.matchbox exists. mkdir() failing because it is
   * already there (or the save failing entirely) is fine -- this is
   * a performance cache, not a correctness requirement. */
  home = mb_util_get_homedir();
  if (home != NULL && home[0] != '\0')
    {
      snprintf(dirpath, sizeof(dirpath), "%s/.matchbox", home);
      mkdir(dirpath, 0755);
    }

  snprintf(tmp_path, sizeof(tmp_path), "%s.tmp", path);

  fp = fopen(tmp_path, "wb");
  if (fp == NULL) return;

  memcpy(hdr, WPCACHE_MAGIC, 4);
  hdr[4] = WPCACHE_VERSION;
  hdr[5] = (unsigned char) mb->pixbuf->internal_bytespp;
  hdr[6] = img->has_alpha ? 1 : 0;
  hdr[7] = 0;
  _put_u32(hdr + 8,  (uint32_t) img->width);
  _put_u32(hdr + 12, (uint32_t) img->height);
  _put_u32(hdr + 16, _hash_spec(mb));
  _put_u32(hdr + 20, (uint32_t) st.st_mtime);

  pixel_bytes = (size_t)img->width * (size_t)img->height
              * (size_t)(mb->pixbuf->internal_bytespp + (img->has_alpha ? 1 : 0));

  if (fwrite(hdr, 1, WPCACHE_HDR_LEN, fp) != WPCACHE_HDR_LEN
      || fwrite(img->rgba, 1, pixel_bytes, fp) != pixel_bytes
      || fflush(fp) != 0)
    {
      fclose(fp);
      unlink(tmp_path);
      return;
    }

  fclose(fp);

  /* Atomic swap -- a boot interrupted mid-write (power loss, this
   * device is fragile) must never leave a half-written cache file
   * that a later boot would try to load. */
  rename(tmp_path, path);
}
